- name: stop splunk
  command: "{{ splunk_home }}/bin/splunk stop"
  become: true

- name: remove splunk user
  user:
    name: splunk
    state: absent
    remove: true
    force: true
  become: true

- name: remove splunklib
  file:
    path: "{{ splunklib_1_6_2_location }}"
    state: absent
