- name: create Cluster Search Head serverclass
  splunk_serverclass:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: Cluster Search Head
    state: present
    whitelists:
        - search*
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: add cluster_searchhead_app to Cluster Search Head serverclass
  splunk_deployment_application:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: cluster_searchhead_app
    serverclass: Cluster Search Head
    state: present
    restartSplunkd: true
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: create Deployment Clients serverclass
  splunk_serverclass:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: Deployment Clients
    state: present
    whitelists:
        - "*"
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: add deployment_client_app to Deployment Clients serverclass
  splunk_deployment_application:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: deployment_client_app
    serverclass: Deployment Clients
    state: present
    restartSplunkd: true
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: create Forwarders serverclass
  splunk_serverclass:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: Forwarders
    state: present
    whitelists:
        - search01
        - forwarder01
        - cluster-master
        - dmc
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: add forwarder_outputs_app to Forwarders serverclass
  splunk_deployment_application:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    name: forwarder_outputs_app
    serverclass: Forwarders
    state: present
    restartSplunkd: true
    splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"
